#!/usr/bin/env python3
"""Split PoseidonBN254.sol into PoseidonT3.sol (hash2+C3) and PoseidonT4.sol
(hash3+C4), hoisting the repeated field-modulus PUSH32 literal into scratch
memory (slot 0x00) so each library's runtime fits the hegota devnet's 2^24 per-tx gas cap
(code deposit costs ~1545 gas/byte there under EIP-8037 accounting).
PoseidonBN254.sol becomes a thin internal wrapper; callers are unchanged."""
import re

SRC = "src/PoseidonBN254.sol"
LIT = "21888242871839275222246405745257275088548364400416034343698204186575808495617"

src = open(SRC).read()

def extract(pattern):
    m = re.search(pattern, src, re.S)
    assert m, pattern[:60]
    return m.group(0)

c3 = extract(r"/// 195 t=3 round constants.*?hex\"[0-9a-f]+\";")
c4 = extract(r"/// 256 t=4 round constants.*?hex\"[0-9a-f]+\";")
h2 = extract(r"/// @notice circomlib Poseidon\(2\).*?\n    \}")
h3 = extract(r"/// @notice circomlib Poseidon\(3\).*?\n    \}")

def hoist(fn):
    # The modulus lives in scratch memory (0x00), not a stack local: a local
    # overflows legacy codegen's stack in hash3, and via-IR emits ~3KB of
    # dispatch glue, both of which push PoseidonT4 past the deploy budget.
    # Writing scratch space is allowed in memory-safe assembly; `bytes memory
    # c = C4` allocates at the free pointer, so 0x00 is free. pow5 reads it
    # into a local once (Yul functions can't reference outer variables).
    body = re.search(r"function pow5\(v\) -> y \{.*?\n            \}", fn, re.S).group(0)
    fn = fn.replace(body, body
                    .replace("-> y {", "-> y {\n                let q := mload(0x00)")
                    .replace(LIT, "q"))
    fn = fn.replace(LIT, "mload(0x00)")
    fn = fn.replace('assembly ("memory-safe") {',
                    'assembly ("memory-safe") {\n            mstore(0x00, ' + LIT + ')')
    return fn

HEADER = """// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

/// @title {name} — circomlib Poseidon t={t} half of PoseidonBN254
/// @notice Split out of PoseidonBN254.sol so each half's runtime fits the
///         hegota devnet's 2^24 per-tx gas cap (EIP-8037 code deposit is
///         ~1545 gas/byte there; the combined library needs ~30M to deploy).
///         Same constants, same rounds, same output; the field-modulus
///         literal is hoisted into a local to shrink code size. Verified by
///         the differential vectors in ../test/PoseidonVectors.t.sol.
/// @dev    GENERATED by split_poseidon.py from PoseidonBN254.sol.
library {name} {{
    {const}

    {fn}
}}
"""

open("src/PoseidonT3.sol", "w").write(
    HEADER.format(name="PoseidonT3", t=3, const=c3, fn=hoist(h2)))
open("src/PoseidonT4.sol", "w").write(
    HEADER.format(name="PoseidonT4", t=4, const=c4, fn=hoist(h3)))

open(SRC, "w").write("""// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

import {PoseidonT3} from "./PoseidonT3.sol";
import {PoseidonT4} from "./PoseidonT4.sol";

/// @title PoseidonBN254 — circomlib's Poseidon, on-chain
/// @notice Facade over PoseidonT3/PoseidonT4 (see those files for the round
///         function). Split so each half deploys under the hegota devnet's
///         2^24 per-tx gas cap; callers and the differential vector tests are
///         unchanged. Inline wrappers compile to one DELEGATECALL per hash,
///         exactly as the pre-split public library did.
library PoseidonBN254 {
    uint256 internal constant P = """ + LIT + """;

    function hash2(uint256 x0, uint256 x1) internal pure returns (uint256) {
        return PoseidonT3.hash2(x0, x1);
    }

    function hash3(uint256 x0, uint256 x1, uint256 x2) internal pure returns (uint256) {
        return PoseidonT4.hash3(x0, x1, x2);
    }
}
""")
print("wrote src/PoseidonT3.sol src/PoseidonT4.sol; rewrote " + SRC)
